name: e_customs
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: 
  shared_preferences: 
  flutter_animate: 
  iconsax_plus: 
  timeago: 
  skeletonizer: 
  get_it: 
  injectable: 


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  injectable_generator:
  build_runner:  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/